name: rivezni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  http: ^1.2.2
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets: 
    - assets/images/flashcard.png
    - assets/images/folder.png